// Mocks generated by Mockito 5.2.0 from annotations
// in hye_grocery/test/application/profile/profile_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:hye_grocery/domain/auth/value_field_objects.dart' as _i6;
import 'package:hye_grocery/domain/profile/i_profile_facade.dart' as _i3;
import 'package:hye_grocery/domain/profile/profile_failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [IProfileFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileFacade extends _i1.Mock implements _i3.IProfileFacade {
  MockIProfileFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>> updateUserProfile(
          {_i6.UserName? userName, _i6.PhoneNumber? phoneNumber}) =>
      (super.noSuchMethod(
          Invocation.method(#updateUserProfile, [],
              {#userName: userName, #phoneNumber: phoneNumber}),
          returnValue: Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>>.value(
              _FakeEither_0<_i5.ProfileFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>> deleteProfileImage(
          {String? imageStorageLocation}) =>
      (super.noSuchMethod(
          Invocation.method(#deleteProfileImage, [],
              {#imageStorageLocation: imageStorageLocation}),
          returnValue: Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>>.value(
              _FakeEither_0<_i5.ProfileFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>> updateProfileImage(
          {String? fileName, _i7.File? file}) =>
      (super.noSuchMethod(
          Invocation.method(
              #updateProfileImage, [], {#fileName: fileName, #file: file}),
          returnValue: Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>>.value(
              _FakeEither_0<_i5.ProfileFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i5.ProfileFailure, _i2.Unit>>);
}
